### ISSUE TITLE
Spacing and font size in footer

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#18]

**Comment by cjspurlock** [comment]
Please use this Everplans logo. It should resolve spacing issues. 

https://github.com/mohankumarac12/OurLifeCovered/blob/master/resources/images/footer-logo.png

**Comment by cjspurlock** [comment]
Please update the Everplans logo with the file linked above.

**Comment by mohankumarac12** [comment]
Integrated Everplans logo
