### ISSUE TITLE
Unexpected code displayed

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#28]
**Steps to reproduce-**
Select “I know how much I need” > proceed till coverage page and click on “Apply now” for “enter your own amount and term”
![screen shot 2017-01-05 at 10 57 26 am](https://cloud.githubusercontent.com/assets/2334188/21689381/c37f16ec-d335-11e6-9f88-e39c5bc5e3ff.png)

**Comment by cjspurlock** [comment]
This happens for both Everplans and Multicarrier versions

**Comment by mohankumarac12** [comment]
Issue has been fixed.
