### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#29]
http://devweb01.eastus.cloudapp.azure.com/everplans/home.do?phoneNo=866-357-8991&src=home

Browser: chrome

During testing this error page is seen 3 times-

![screen shot 2017-01-05 at 10 58 55 am](https://cloud.githubusercontent.com/assets/2334188/21689453/f730caee-d335-11e6-9ce3-75598b2c5fcf.png)

**Comment by mohankumarac12** [comment]
Environment specific issue. Not able to reproduce Today.
