### ISSUE TITLE
Dropdown arrow in IE browser

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#30]
![screen shot 2017-01-05 at 10 59 56 am](https://cloud.githubusercontent.com/assets/2334188/21689490/1cd2c23e-d336-11e6-9a64-75532a23c0d8.png)

**Comment by cjspurlock** [comment]
Fixed by updating olc.css. Find revised code here: https://github.com/mohankumarac12/OurLifeCovered/commit/8d924452baa6503bc41cdfb87165c3c3578509e7

**Comment by mohankumarac12** [comment]
Chris code has been incorporated. Fixed.
