### ISSUE TITLE
X symbol in text box in IE

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#31]
![screen shot 2017-01-05 at 11 00 35 am](https://cloud.githubusercontent.com/assets/2334188/21689513/361d272a-d336-11e6-9e7b-09e3e98dc62d.png)

**Comment by cjspurlock** [comment]
Fixed by updating olc.css. Find revised code here: https://github.com/mohankumarac12/OurLifeCovered/commit/8d924452baa6503bc41cdfb87165c3c3578509e7

**Comment by mohankumarac12** [comment]
Chris code has been incorporated. Fixed.
