### ISSUE TITLE
Incorrect font

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#34]
Site is calling TypeKit kit with ID yty8keo. I don't believe this is the right kit. A new kit needs to be set up that includes Open Sans. See screenshots for correct kit setup.
<img width="796" alt="screen shot 2017-01-05 at 11 40 25 am" src="https://cloud.githubusercontent.com/assets/2334188/21734158/87d3279e-d427-11e6-9dab-ebdbc36ee5e8.png">
<img width="597" alt="screen shot 2017-01-05 at 11 41 23 am" src="https://cloud.githubusercontent.com/assets/2334188/21734163/8e77ddb0-d427-11e6-8361-d8b24a369a92.png">

**Comment by cjspurlock** [comment]
The domains listed in the screenshot above may not actually be the domains you want. Please double check and verify all domains you list in your kit.

**Comment by mohankumarac12** [comment]
Fixed the typekit font issue.
