### ISSUE TITLE
Everplans & multi, down arrow missing in IE on landing page

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/ourlivescovered#35]
Journeys appear when box clicked

**Comment by cjspurlock** [comment]
Should be fixed with the updated CSS here: https://github.com/mohankumarac12/OurLifeCovered/commit/618c8e61b8bc2ca6e28841bee76370351e14973d

**Comment by mohankumarac12** [comment]
Integrated the updated CSS code.

**Comment by mohankumarac12** [comment]
its working in both Chrome and IE.
